name: Run url checks

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: urlchecker
      uses: urlstechie/urlchecker-action@0.1.7
      with:
        # The project base path.
        git_path: https://github.com/urlstechie/urlchecker-test-repo
        
        # A comma-separated list of file types to cover in the URL checks
        file_types: .md,.py,.rst
      
        # Choose whether to include file with no URLs in the prints.
        print_all: false

        # The timeout seconds to provide to requests, defaults to 5 seconds
        timeout: 5

        # How many times to retry a failed request (each is logged, defaults to 1)
        retry_count: 3

        # A comma separated links to exclude during URL checks
        white_listed_urls: https://superkogito.github.io/figures/fig2.html, https://superkogito.github.io/figures/fig4.html

        # A comma separated patterns to exclude during URL checks
        white_listed_patterns: https://superkogito.github.io/tables
      
        # choose if the force pass or not 
        force_pass: false
